version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.4

  kafka:
    image: confluentinc/cp-kafka:5.2.4
    depends_on:
      - zookeeper

  eventuate-cdc:
    depends_on:
      - mssql-db
      - kafka
      - zookeeper
    image: eventuateio/eventuate-cdc-service:latest

  infrastructure-apigw:
    image: envoyproxy/envoy-alpine:v1.16-latest

  blogging-apigw:
    image: envoyproxy/envoy-alpine:v1.16-latest

  mssql-db:
    image: mcr.microsoft.com/mssql/server:2017-latest

  identity-server-api:
    image: brevien/identity-server.api
    build:
      context: .
      dockerfile: Services/IdentityServer/IdentityServer.API/Dockerfile
    depends_on:
      - mssql-db
      - kafka
      - zookeeper

  identity-control-api:
    image: brevien/identity-control.api
    build:
      context: .
      dockerfile: Services/IdentityControl/IdentityControl.API/Dockerfile
    depends_on:
      - mssql-db
      - kafka
      - zookeeper

  blogging-api:
    image: brevien/blogging.api
    build:
      context: .
      dockerfile: Services/Blogging/Blogging.API/Dockerfile
    depends_on:
      - mssql-db
      - kafka
      - zookeeper

  posting-api:
    image: brevien/posting.api
    build:
      context: .
      dockerfile: Services/Posting/Posting.API/Dockerfile
    depends_on:
      - mssql-db
      - kafka
      - zookeeper
