version: '3.8'

services:
  infrastructure-apigw:
    volumes:
      - ./ApiGateways/Envoy/https.crt:/etc/ssl/certs/https.crt
      - ./ApiGateways/Envoy/key.pem:/etc/ssl/certs/key.pem
      - ./ApiGateways/Envoy/Infrastructure:/etc/envoy
    ports:
      - "9901:9901"
      - "8000:8000"

  blogging-apigw:
    volumes:
      - ./ApiGateways/Envoy/https.crt:/etc/ssl/certs/https.crt
      - ./ApiGateways/Envoy/key.pem:/etc/ssl/certs/key.pem
      - ./ApiGateways/Envoy/Blogging:/etc/envoy
    ports:
      - "9911:9901"
      - "8010:8010"

  sqldata:
    environment:
      - SA_PASSWORD=SqlS3rv3r#34
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - brevien-sqldata:/var/opt/mssql

  nosqldata:
    ports:
      - "27018:27017"
    volumes:
      - brevien-nosqldata:/data/db

  identity-server-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ApplicationUrls__IdentityControl__Origin=https://localhost:8000
      - ApplicationUrls__IdentityControl__Path=/ic
      - ApplicationUrls__Blogging__Origin=https://localhost:8010
      - ApplicationUrls__Blogging__Path=/b
      - ApplicationUrls__Posting__Origin=https://localhost:8010
      - ApplicationUrls__Posting__Path=/p
      - ConnectionString=Server=sqldata;Database=brevien-identity-local;User Id=SA;Password=SqlS3rv3r#34
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pa55w0rd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5001:443"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro

  identity-control-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApplicationUrls__IdentityControl=https://localhost:8000
      - ApplicationUrls__Authority=http://identity-server-api
      - PATH_BASE=/ic
      - ConnectionString=Server=sqldata;Database=brevien-identity-local;User Id=SA;Password=SqlS3rv3r#34
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro

  blogging-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApplicationUrls__Blog=https://localhost:8010
      - ApplicationUrls__Authority=http://identity-server-api
      - PATH_BASE=/b
      - MongoDb__ConnectionString=mongodb://nosqldata
      - MongoDb__Database=brevien-blog-local
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro

  posting-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ApplicationUrls__Posting=https://localhost:8010
      - ApplicationUrls__Authority=http://identity-server-api
      - PATH_BASE=/p
      - Persistence__Server=Server=sqldata;User Id=SA;Password=SqlS3rv3r#34
      - Persistence__DatabaseName=brevien-posting-local
      - Persistence__ConnectionString=Server=sqldata;Database=brevien-posting-local;User Id=SA;Password=SqlS3rv3r#34
      - Http__Blogging__BaseUri=http://blogging-api
      - Http__Blogging__Headers__SecretKey__Value=blog-secret
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https:ro

volumes:
  brevien-sqldata:
  brevien-nosqldata:
